version: '3.8'

services:
  jasperserver:
    image: retriever/jasperserver:latest
    container_name: jasperserver
    ports:
      - "9001:8080"
    environment:
      - DB_TYPE=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
    driver: local
