version: '3.6'

services:
  keycloak_web:
    image: quay.io/keycloak/keycloak:25.0.2
    container_name: keycloak_web
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloakdb:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password

      KC_HOSTNAME: kc.mindtechpy.net
      KC_HOSTNAME_PORT: 5002
      KC_HOSTNAME_STRICT: "false"
      KC_HOSTNAME_STRICT_HTTPS: "false"
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: "true"
      KC_HEALTH_ENABLED: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: KeycloakServer761995!
      KC_FEATURES: token-exchange
      FEATURES: token-exchange
      JAVA_TOOL_OPTIONS: "-Dkeycloak.profile.feature.admin_fine_grained_authz=enabled -Dkeycloak.profile.feature.token_exchange=enabled"
      KC_PROXY: "edge"

    command: start-dev
    depends_on:
      - keycloakdb
    ports:
      - 5002:8080
    restart: always  # Añadir política de reinicio

  keycloakdb:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    restart: always  # Añadir política de reinicio

volumes:
  postgres_data:
