version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    ports:
      - "8000:9000"
      - "8001:9001"
    environment:
      MINIO_ROOT_USER: root
      MINIO_ROOT_PASSWORD: Password
    volumes:
      - ~/minio/data:/data
    command: server /data --console-address ":9001"