version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --requirepass HolaMundo
    volumes:
      - redis_data:/data

volumes:
  redis_data: